export const events = [
  {
    'Data': '2026-02-22',
    'Inicio': '09:00',
    'Fim': '14:00',
    'Titulo': 'CAASO Vive',
    'Descricao': '',
    'Local': 'Palquinho do CAASO',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '08:00',
    'Fim': '09:30',
    'Titulo': 'Abertura',
    'Descricao': '',
    'Local': 'Salão de Eventos USP - São Carlos',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '10:00',
    'Fim': '12:00',
    'Titulo': 'Entrega do Kit Ingressante',
    'Descricao': '',
    'Local': 'Vão da Biblioteca',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '10:00',
    'Fim': '12:00',
    'Titulo': 'Conversa com os pais',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '10:00',
    'Fim': '11:30',
    'Titulo': 'Doação de Materiais Escolares e Didáticos',
    'Descricao': '',
    'Local': 'Vão da Biblioteca',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '12:00',
    'Fim': '14:00',
    'Titulo': 'Almoço',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '12:00',
    'Fim': '14:00',
    'Titulo': 'Integra Redondo (PET)',
    'Descricao': '',
    'Local': 'Redondo',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '14:00',
    'Fim': '18:00',
    'Titulo': 'Gincana de Integração e Apresentação do ICMC',
    'Descricao': '',
    'Local': 'Concentração no Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '18:00',
    'Fim': '19:00',
    'Titulo': 'Entrega do Kit Ingressante',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '18:00',
    'Fim': '19:00',
    'Titulo': 'Jantar',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '19:00',
    'Fim': '20:00',
    'Titulo': 'Abertura do ICMC',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '20:00',
    'Fim': '20:30',
    'Titulo': 'Apresentação do Caça-Links',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-23',
    'Inicio': '20:30',
    'Fim': '22:00',
    'Titulo': 'CineCAASO com PET',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '08:30',
    'Fim': '10:30',
    'Titulo': 'Bate-Papo com Veteranos',
    'Descricao': '',
    'Local': 'BCC  (sala 4-001), MAT-NG (sala 3-011), BCDados (sala 3-012), BMACC (sala 4-005)',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '10:30',
    'Fim': '12:00',
    'Titulo': 'Bate-Papo com Coordenação',
    'Descricao': '',
    'Local': 'BCC (sala 4-001), MAT-NG (sala 3-011), BCDados (sala 3-012), BMACC (sala 4-005)',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '12:00',
    'Fim': '14:00',
    'Titulo': 'Almoço',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '14:00',
    'Fim': '18:00',
    'Titulo': 'Tô à Toa',
    'Descricao': '',
    'Local': 'Evento no Campus II - concentração às 14h no redondo',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '18:00',
    'Fim': '19:30',
    'Titulo': 'Jantar',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '19:30',
    'Fim': '21:00',
    'Titulo': 'Bate-Papo com Veteranos',
    'Descricao': '',
    'Local': 'BSI (sala 3-009), BECD (sala 3-011)',
    'type': '1',
  },
  {
    'Data': '2026-02-24',
    'Inicio': '21:00',
    'Fim': '22:30',
    'Titulo': 'Bate-Papo com Coordenação',
    'Descricao': '',
    'Local': 'BSI (sala 3-009), BECD (sala 3-011)',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '09:00',
    'Fim': '10:00',
    'Titulo': 'Palestra: Prof. Marcos Arenales',
    'Descricao': 'Título: Escolhas',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '10:00',
    'Fim': '10:30',
    'Titulo': 'Apresentação do Aloja',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '10:30',
    'Fim': '11:00',
    'Titulo': 'Inclusão e Pertencimento + Serviço Social',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '11:00',
    'Fim': '12:00',
    'Titulo': 'GAPSi + ProEstudo',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '12:00',
    'Fim': '13:30',
    'Titulo': 'Almoço',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '12:00',
    'Fim': '13:30',
    'Titulo': 'Integra Redondo (PET)',
    'Descricao': '',
    'Local': 'Redondo',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '13:30',
    'Fim': '14:30',
    'Titulo': 'Palestra CCEx',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '14:30',
    'Fim': '17:00',
    'Titulo': 'Feira de Extracurriculares',
    'Descricao': '',
    'Local': 'Vão da biblioteca',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '17:00',
    'Fim': '18:00',
    'Titulo': 'Jantar',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-25',
    'Inicio': '18:00',
    'Fim': '21:00',
    'Titulo': 'Aulão de Matemática, Estatística e Computação',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '09:00',
    'Fim': '10:30',
    'Titulo': 'Seminário de Coisas Legais',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '10:30',
    'Fim': '11:00',
    'Titulo': 'Palestra da Comunicação',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '11:00',
    'Fim': '12:00',
    'Titulo': 'Final do Torneio de Jogos do Museu',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '12:00',
    'Fim': '13:30',
    'Titulo': 'Almoço',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '13:30',
    'Fim': '14:30',
    'Titulo': 'Palestra sobre História da USP e do Campus de São Carlos',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '14:30',
    'Fim': '15:00',
    'Titulo': 'Direcionamento para o início do semestre',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '15:00',
    'Fim': '17:30',
    'Titulo': 'Visita integrada à Biblioteca',
    'Descricao': '',
    'Local': 'Concentração às 15h no Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '17:30',
    'Fim': '18:00',
    'Titulo': 'Premiação do Caça Links',
    'Descricao': '',
    'Local': 'Auditório Fernão',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '18:00',
    'Fim': '19:00',
    'Titulo': 'Jantar',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
  {
    'Data': '2026-02-26',
    'Inicio': '19:30',
    'Fim': '22:30',
    'Titulo': 'Gamenight e encontro de Clubes do ICMC',
    'Descricao': '3009/3010/3011/3012',
    'Local': 'Bloco 3',
    'type': '1',
  },
  {
    'Data': '2026-02-27',
    'Inicio': '21:00',
    'Fim': '03:00',
    'Titulo': 'Gamenight do CAASO',
    'Descricao': '',
    'Local': '',
    'type': '1',
  },
];
