export const events = [
  {
    Data: '2025-02-24',
    Inicio: '08:00',
    Fim: '09:30',
    Titulo: 'Abertura',
    Descricao: 'Evento de abertura da Semana de Recepção',
    Local: 'Salão de Eventos USP - São Carlos',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '10:00',
    Fim: '12:00',
    Titulo: 'Entrega do Kit Ingressante',
    Descricao: '',
    Local: 'Vão da Biblioteca',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '10:00',
    Fim: '12:00',
    Titulo: 'Conversa com os pais',
    Descricao: 'Orientações e esclarecimentos',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '10:00',
    Fim: '12:00',
    Titulo: 'Trote Solidário',
    Descricao: 'Doação de cabelo (PET) e montagem de caixas para campanha do agasalho',
    Local: 'Vão da Biblioteca',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '12:00',
    Fim: '14:00',
    Titulo: 'Integra Redondo (PET)',
    Descricao: 'Eventos para integração dos novos alunos',
    Local: 'Espaço Redondo (Bloco 4 do ICMC)',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '14:00',
    Fim: '18:00',
    Titulo: 'Gincana de Integração e Apresentação do ICMC',
    Descricao: 'Atividades interativas e apresentação institucional',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '18:00',
    Fim: '19:00',
    Titulo: 'Entrega do Kit Ingressante',
    Descricao: 'Distribuição de kits para novos alunos',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '19:00',
    Fim: '19:30',
    Titulo: 'Abertura do ICMC',
    Descricao: 'Cerimônia de abertura',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-24',
    Inicio: '19:30',
    Fim: '20:00',
    Titulo: 'Apresentação do Caça-Links',
    Descricao: 'Introdução e início do evento Caça-Links',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-25',
    Inicio: '09:00',
    Fim: '10:30',
    Titulo: 'Bate Papo com Veteranos',
    Descricao: 'Conversa com veteranos sobre a experiência acadêmica, compartilhando dicas e histórias',
    Local: 'BCC - Sala 4-001, MAT-NG - Sala 3-011, BCD - Sala 3-012, BMACC - Sala 4-005',
    type: '1',
  },
  {
    Data: '2025-02-25',
    Inicio: '10:30',
    Fim: '12:00',
    Titulo: 'Bate Papo com a Coordenação',
    Descricao: 'Sessão de perguntas e respostas com a coordenação',
    Local: 'BCC - Sala 4-001, MAT-NG - Sala 3-011, BCD - Sala 3-012, BMACC - Sala 4-005',
    type: '1',
  },
  {
    Data: '2025-02-25',
    Inicio: '14:00',
    Fim: '18:00',
    Titulo: 'To à Toa',
    Descricao: 'Evento descontraído no Campus II',
    Local: 'Concentração às 14h no espaço redondo (Bloco 4 do ICMC)',
    type: '1',
  },
  {
    Data: '2025-02-25',
    Inicio: '19:30',
    Fim: '21:00',
    Titulo: 'Bate Papo com Veteranos (cursos noturnos)',
    Descricao: 'Conversa com veteranos sobre a experiência acadêmica, compartilhando dicas e histórias',
    Local: 'BSI (Sala 3-009), BCED (Sala 3-011)',
    type: '1',
  },
  {
    Data: '2025-02-25',
    Inicio: '21:00',
    Fim: '22:30',
    Titulo: 'Bate Papo com Coordenação (cursos noturnos)',
    Descricao: 'Conversa com a coordenação sobre a estrutura dos cursos',
    Local: 'BSI (Sala 3-009), BCED (Sala 3-011)',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '09:00',
    Fim: '10:00',
    Titulo: 'Palestra: Desafios da Computação na Atualidade',
    Descricao: 'Palestrante: Professora Maria da Graça',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '10:00',
    Fim: '11:00',
    Titulo: 'Inclusão e Pertencimento + Aloja + Serviço Social',
    Descricao: '',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '11:00',
    Fim: '12:00',
    Titulo: 'GAPSi + ProEstudo',
    Descricao: 'Discussão sobre suporte acadêmico e psicológico',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '12:00',
    Fim: '14:00',
    Titulo: 'Integra Redondo (PET)',
    Descricao: 'Eventos para integração dos novos alunos',
    Local: 'Espaço Redondo (Bloco 4 do ICMC)',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '13:30',
    Fim: '14:30',
    Titulo: 'Palestra CCEX',
    Descricao: '',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '14:30',
    Fim: '17:00',
    Titulo: 'Feira de extracurriculares',
    Descricao: 'Exposição de grupos e atividades extracurriculares',
    Local: 'Vão da Biblioteca',
    type: '1',
  },
  {
    Data: '2025-02-26',
    Inicio: '18:00',
    Fim: '21:00',
    Titulo: 'Aulão de Matemática/Estatística/Computação',
    Descricao: 'Aula introdutório para os novos alunos',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '08:30',
    Fim: '10:00',
    Titulo: 'Seminário das coisas legais',
    Descricao: '',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '10:00',
    Fim: '10:30',
    Titulo: 'Premiação do Caça Links',
    Descricao: '',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '10:30',
    Fim: '12:00',
    Titulo: 'Prêmio J.F. Marar de Inteligência Artificial',
    Descricao: '',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '14:30',
    Fim: '15:00',
    Titulo: 'Direcionamento para o início do semestre',
    Descricao: '',
    Local: 'Auditório Fernão',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '15:00',
    Fim: '18:00',
    Titulo: 'PET - Oficina',
    Descricao: 'Oficina organizada pelo grupo PET',
    Local: 'Vão da Biblioteca',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '15:00',
    Fim: '18:00',
    Titulo: 'Visita integrada à biblioteca',
    Descricao: 'Visitas guiadas em grupos pela biblioteca',
    Local: 'Biblioteca Achille Bassi',
    type: '1',
  },
  {
    Data: '2025-02-27',
    Inicio: '19:30',
    Fim: '22:30',
    Titulo: 'Game Night + Clubes',
    Descricao: 'Atividades do Clube de Crochê, Clube de Inglês, Clube de Xadrez e Clube de Leitura',
    Local: 'Bloco 3: salas 3009/3010/3011/3012',
    type: '1',
  },
];
