export const scheduleContent = [
  {
    id: 0,
    events: [
      {
        id: 0,
        timeBegin: '08:00',
        timeEnd: '10:00',
        title: 'Abertura conjunta',
        description: 'Atividade para todos os ingressantes do Campus USP São Carlos e seus familiares, com as presenças de dirigentes',
        place: 'Salão de eventos do Campus',
        type: '1',
      },
      {
        id: 1,
        timeBegin: '10:00',
        timeEnd: '12:00',
        title: 'Bate-papo com os pais, professores e coordenadores de curso',
        description: 'O evento ocorrerá em paralelo a atividades do Centro Acadêmico com os alunos',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
      {
        id: 2,
        timeBegin: '18:00',
        timeEnd: '20:00',
        title: 'Recepção do ICMC',
        description: 'Boas-vindas: agora você faz parte do ICMC',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
    ],
  },
  {
    id: 1,
    events: [
      {
        id: 0,
        timeBegin: '08:00',
        timeEnd: '10:00',
        title: 'Matrícula presencial',
        description: 'Cursos da área de Matemática (Núcleo Geral e Matemática Aplicada e Computação Científica) e do curso de Ciências de Computação',
        place: 'Anfiteatro Jorge Caron',
        type: '1',
      },
      {
        id: 1,
        timeBegin: '08:00',
        timeEnd: '10:00',
        title: 'Bate-papo com a coordenação',
        description: 'Curso de Engenharia de Computação',
        place: 'Bloco 4 do ICMC (sala 4-001)',
        type: '2',
      },
      {
        id: 2,
        timeBegin: '10:00',
        timeEnd: '12:00',
        title: 'Matrícula presencial',
        description: 'Curso de Engenharia de Computação',
        place: 'Anfiteatro Jorge Caron',
        type: '1',
      },
      {
        id: 3,
        timeBegin: '10:00',
        timeEnd: '12:00',
        title: 'Bate-papo com a coordenação',
        description: 'Curso de Ciências de Computação',
        place: 'Bloco 4 do ICMC (sala 4-003)',
        type: '2',
      },
      {
        id: 4,
        timeBegin: '10:00',
        timeEnd: '12:00',
        title: 'Bate-papo com a coordenação',
        description: 'Cursos de Matemática (Núcleo Geral e Matemática Aplicada e Computação Científica)',
        place: 'Bloco 4 do ICMC (sala 4-001)',
        type: '2',
      },
      {
        id: 5,
        timeBegin: '18:00',
        timeEnd: '19:00',
        title: 'Bate-papo com a coordenação',
        description: 'Curso de Estatística e Ciência de Dados',
        place: 'Bloco 4 do ICMC (sala 4-003)',
        type: '2',
      },
      {
        id: 6,
        timeBegin: '18:00',
        timeEnd: '19:00',
        title: 'Bate-papo com a coordenação',
        description: 'Curso de Sistemas de Informação',
        place: 'Bloco 4 do ICMC (sala 4-005)',
        type: '2',
      },
      {
        id: 7,
        timeBegin: '19:00',
        timeEnd: '21:00',
        title: 'Matrícula presencial',
        description: 'Cursos de Estatística e Ciência de Dados e Sistemas de Informação',
        place: 'Anfiteatro Jorge Caron',
        type: '1',
      },
    ],
  },
  {
    id: 2,
    events: [
      {
        id: 0,
        timeBegin: '08:00',
        timeEnd: '10:00',
        title: 'Matrícula presencial',
        description: 'Cursos da área de Matemática (Núcleo Geral e Matemática Aplicada e Computação Científica) e do curso de Ciências de Computação',
        place: 'Anfiteatro Jorge Caron',
        type: '1',
      },
      {
        id: 1,
        timeBegin: '09:00',
        timeEnd: '12:00',
        title: 'Feira de oportunidades',
        description: 'Conheça as diversas oportunidades oferecidas aos alunos de graduação e saiba mais sobre os grupos de extensão',
        place: 'Hiperespaço Gilberto Loibel',
        type: '2',
      },
      {
        id: 2,
        timeBegin: '10:00',
        timeEnd: '12:00',
        title: 'Matrícula presencial',
        description: 'Curso de Engenharia de Computação',
        place: 'Anfiteatro Jorge Caron',
        type: '1',
      },
      {
        id: 3,
        timeBegin: '18:00',
        timeEnd: '21:00',
        title: 'Aulas introdutórias',
        description: 'As primeiras aulas no ICMC a gente nunca esquece: assista a três aulas introdutórias sobre computação, matemática e estatística',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
      {
        id: 4,
        timeBegin: '19:00',
        timeEnd: '21:00',
        title: 'Matrícula presencial',
        description: 'Cursos de Estatística e Ciência de Dados e Sistemas de Informação',
        place: 'Anfiteatro Jorge Caron',
        type: '1',
      },
      {
        id: 5,
        timeBegin: '21:00',
        timeEnd: '00:00',
        title: 'Luau e Gincana',
        description: 'Faça parte dessa diversão',
        place: 'Jardim secreto do ICMC',
        type: '2',
      },
    ],
  },
  {
    id: 3,
    events: [
      {
        id: 0,
        timeBegin: '09:00',
        timeEnd: '11:00',
        title: 'Bate-papo com alunos experientes',
        description: 'Aprenda com quem já foi calouro',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
      {
        id: 1,
        timeBegin: '11:00',
        timeEnd: '12:00',
        title: 'Bate-papo',
        description: 'Ufa, passei! E agora? Promovendo a saúde mental na Universidade',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
      {
        id: 2,
        timeBegin: '12:00',
        timeEnd: '19:00',
        title: 'Trote solidário / Ambiental',
        place: 'Local a ser definido',
        type: '2',
      },
      {
        id: 3,
        timeBegin: '19:00',
        timeEnd: '00:00',
        title: 'Game Night',
        description: 'Sua primeira noite de jogos no ICMC',
        place: 'Jardim secreto do ICMC',
        type: '2',
      },
    ],
  },
  {
    id: 4,
    events: [
      {
        id: 0,
        timeBegin: '11:11',
        timeEnd: '12:00',
        title: 'Seminário de Coisas Legais',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
      {
        id: 1,
        timeBegin: '12:00',
        timeEnd: '13:00',
        title: 'Encerramento',
        description: 'Premiação para os alunos que conquistaram mais pontos no jogo Bixoquest',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
    ],
  },
  {
    id: 5,
    events: [
      {
        id: 0,
        timeBegin: '13:00',
        timeEnd: '14:00',
        title: 'Bate-papo',
        description: 'Por aqui, a gente se comunica e você faz parte de tudo isso!',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
    ],
  },
  {
    id: 6,
    events: [
      {
        id: 0,
        timeBegin: '13:00',
        timeEnd: '14:00',
        title: 'Bate-papo',
        description: 'Eu também faço parte de tudo isso: uma visão organizacional da USP',
        place: 'Auditório Fávaro',
        type: '2',
      },
    ],
  },
  {
    id: 7,
    events: [
      {
        id: 0,
        timeBegin: '13:00',
        timeEnd: '14:00',
        title: 'Atividades lúdicas e de saúde mental',
        place: 'Auditório Fernão Stella',
        type: '2',
      },
    ],
  },
  {
    id: 8,
    events: [
      {
        id: 0,
        timeBegin: '13:00',
        timeEnd: '14:00',
        title: 'Encontro especial para quem não participou da Semana de Recepção',
        place: 'Em breve',
        type: '2',
      },
    ],
  },
];

export const steps = ['17/02 (Seg)', '18/02 (Ter)', '19/02 (Qua)', '20/02 (Qui)', '21/02 (Sex)', '04/03 (Qua)', '11/03 (Qua)', '18/03 (Qua)', '25/03 (Qua)'];

export const stepContent = ['17/02 - Segunda-feira', '18/02 - Terça-feira', '19/02 - Quarta-feira', '20/02 - Quinta-feira', '21/02 - Sexta-feira', '04/03 - Quarta-feira', '11/03 - Quarta-feira', '18/03 - Quarta-feira', '25/03 - Quarta-feira'];
